//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by Á·×Ö¹¤¾ß.rc
//
#define IDOK2                           2
#define ID_LICENSE                      2
#define IDD_ABOUTBOX                    100
#define IDP_OLE_INIT_FAILED             100
#define IDS_LINE_COLOR                  101
#define IDS_GRID_LINE                   102
#define IDS_GRID_SIZE                   103
#define IDD_HARDWARE                    103
#define IDS_FONT_COLOR                  104
#define IDS_GRID_ROWSPACE               105
#define IDS_GRID_COLSPACE               106
#define IDS_GRID_SIZE_SPACE             107
#define IDS_FONT_HOLLOW                 108
#define IDS_FONT_PREVIEW                109
#define IDB_WRITESMALL                  110
#define IDS_CHAR_SAMPLE                 110
#define IDB_WRITELARGE                  111
#define IDS_CHAR_SAMPLE_DES             111
#define IDB_MAIN                        112
#define IDS_CHAR_DIRECT1                112
#define IDB_BUTTONS                     113
#define IDS_CHAR_DIRECT2                113
#define IDB_FILELARGE                   114
#define IDS_CHAR_DIRECT3                114
#define IDB_FILESMALL                   115
#define IDS_CHAR_DIRECT4                115
#define IDS_CHAR_DIRECT                 116
#define IDS_PAGE_LAYOUT                 117
#define IDS_CHAR_HEIGHT_SCOPE           118
#define IDS_IMGTOOLARGE                 118
#define IDR_POPUP_EDIT                  119
#define IDS_PAPER_PORTRAIT              119
#define IDS_PAPER_LANDSCAPE             120
#define IDS_PAPER_ORIENT                121
#define IDS_STATUS_PANE1                122
#define IDS_PREVIES_PAGEINFOR           123
#define IDS_PREVIEW_PAGE_INFOR          123
#define IDS_NUMBER_SCOPE_MSG            124
#define IDS_SETTING_INVALID             125
#define IDS_HUI_GRID_STYLE              126
#define IDS_HUI_IN_OUT_RATE             127
#define IDR_MAINFRAME                   128
#define IDR_MAINFRAME_256               129
#define IDS_HUI_W_H_RATE                129
#define IDR_MyTYPE                      130
#define IDS_HUI_OFFSETY                 130
#define IDS_CHAR_OFFSETY                131
#define IDS_TASKPANE_GRIDSPLIT          132
#define IDS_TASKPANE_GRIDSPLIT2         133
#define IDS_EDITGRIDIMG                 134
#define IDS_SAVEGRIDIMG                 135
#define IDS_OPENGRIDIMG                 136
#define IDS_SELECTBACKGROUND            137
#define IDS_NOBACKCOLOR                 138
#define IDS_OTHERCOLOR                  139
#define IDS_WMI_MSG                     140
#define IDS_HAS_LICENCE                 141
#define IDS_NO_LICENCE                  142
#define IDS_REGISTER_OK                 143
#define IDS_REGISTER_FAIL               144
#define IDS_DONT_PRINT_MSG              145
#define IDS_WATERMARK                   146
#define IDS_REGISTER_PROMPT             147
#define IDS_LANGUAGE                    148
#define IDR_PASTE_MENU                  151
#define IDR_WINDOWS_MENU                152
#define ID_VIEW_NAVIGATION              185
#define IDR_THEME_MENU                  200
#define ID_VIEW_APPLOOK_WIN_2000        210
#define ID_VIEW_APPLOOK_OFF_XP          211
#define ID_VIEW_APPLOOK_WIN_XP          212
#define ID_VIEW_APPLOOK_OFF_2003        213
#define ID_VIEW_APPLOOK_VS_2005         214
#define ID_VIEW_APPLOOK_OFF_2007_BLUE   215
#define ID_VIEW_APPLOOK_OFF_2007_BLACK  216
#define ID_VIEW_APPLOOK_OFF_2007_SILVER 217
#define ID_VIEW_APPLOOK_OFF_2007_AQUA   218
#define ID_TOOLS_OPTIONS                220
#define ID_VIEW_CAPTION_BAR             221
#define IDS_CAPTION_BUTTON              231
#define IDS_CAPTION_BUTTON_TIP          232
#define IDS_CAPTION_TEXT                233
#define IDS_CAPTION_IMAGE_TIP           234
#define IDS_CAPTION_IMAGE_TEXT          235
#define IDS_VIEW_TASK_PANE              236
#define IDS_TASKPANE_OPENFILE           237
#define IDS_TASKPANE_MOREFILE           238
#define IDS_TASKPANE_COPYBOOK           239
#define IDS_MYCALENDARS                 250
#define IDS_CALENDAR                    251
#define IDS_SHORTCUTS                   252
#define IDS_FOLDERS                     253
#define IDS_FONT_NAME                   254
#define IDS_FONT_HEIGTH                 255
#define IDS_FONT_BOLD                   256
#define IDS_FONT_SOLID                  257
#define IDS_OUTLOOKBAR                  258
#define IDS_RIBBON_FILE                 260
#define IDS_RIBBON_NEW                  262
#define IDS_RIBBON_OPEN                 263
#define IDS_RIBBON_SAVE                 264
#define IDS_RIBBON_SAVEAS               265
#define IDS_RIBBON_PRINT                266
#define IDS_RIBBON_PRINT_LABEL          267
#define IDS_RIBBON_PRINT_QUICK          268
#define IDS_RIBBON_PRINT_PREVIEW        269
#define IDS_RIBBON_PRINT_SETUP          270
#define IDS_RIBBON_CLOSE                271
#define IDS_RIBBON_RECENT_DOCS          272
#define IDS_RIBBON_EXIT                 273
#define IDS_RIBBON_HOME                 274
#define IDS_RIBBON_CLIPBOARD            275
#define IDS_RIBBON_PASTE                276
#define IDS_RIBBON_CUT                  277
#define IDS_RIBBON_COPY                 278
#define IDS_RIBBON_SELECTALL            279
#define IDS_RIBBON_WINDOW               284
#define IDS_RIBBON_WINDOWS              285
#define IDS_RIBBON_STYLE                286
#define IDS_RIBBON_STYLE_TIP            287
#define IDS_RIBBON_STYLE_DESC           288
#define IDS_RIBBON_STATUSBAR            289
#define IDS_RIBBON_VIEW                 290
#define IDS_RIBBON_CAPTIONBAR           295
#define IDS_EDIT_MENU                   306
#define IDS_RIBBON_GRID_STYLE           307
#define IDS_RIBBON_CHAR_STYLE           308
#define IDS_GRID_CATEGORY               309
#define IDS_GRID_CATEGORY_TIAN          310
#define IDB_GRID_STYLE                  310
#define IDS_GRID_CATEGORY_MI            311
#define IDS_GRID_CATEGORY_SPACE         312
#define IDS_GRID_CATEGORY_JIU           313
#define IDS_GRID_CATEGORY_HUI           314
#define IDB_GRID_CATEGORY2              314
#define IDS_FILE_TOOLARGE               315
#define IDB_GRID_STYLE_SMALL            315
#define IDS_FILE_PAGE_SETUP             316
#define IDB_BITMAP1                     316
#define IDB_PAGE_LAYOUT                 316
#define IDS_CHAR_STYLE_FONT             317
#define IDB_CHAR_STYLE                  317
#define IDS_PAGE_MARGIN                 318
#define IDB_GRID_HUI_STYLE              318
#define IDS_PAGE_MARGIN_TOP             319
#define IDB_GRID_HUI_STYLE_SMALL        319
#define IDS_PAGE_MARGIN_BOTTOM          320
#define IDI_TASKPANE_OPENFILE           320
#define IDS_PAGE_MARGIN_LEFT            321
#define IDB_PAGELAYOUT_SMALL            321
#define IDS_PAGE_MARGIN_RIGHT           322
#define IDC_ZOOMOUT                     322
#define IDS_PAGE_CENTER                 323
#define IDC_ZOOMIN                      323
#define IDS_PAGE_CENTER_HORZ            324
#define IDS_PAGE_CENTER_VERT            325
#define IDS_OWNERDRAWGRID               326
#define IDS_OWNERDRAW                   327
#define IDS_OWNGRIDSELECTMSG            328
#define IDB_BACKCOLOR                   330
#define IDB_BACKCOLOR_SMALL             331
#define IDC_LICENSE_INFOR               1000
#define IDC_EDIT1                       1003
#define IDC_SAVE                        1004
#define IDC_COPY                        1005
#define IDC_MACHINE_ID                  1005
#define ID_COMMAND_MIN                  32000
#define ID_WRITE_PASTEASHYPERLINK       32770
#define ID_GRID_CATEGORY                32772
#define ID_CHAR_STYLE_FONT              32776
#define ID_CHAR_STYLE_HEIGHT            32777
#define ID_CHAR_STYLE_WEIGHT            32779
#define IDR_GRID                        32784
#define ID_32795                        32795
#define ID_LINE_COLOR                   32796
#define ID_32797                        32797
#define IDS_LINE_STYLE                  32798
#define ID_32799                        32799
#define ID_GIRD_SIZE                    32801
#define ID_32802                        32802
#define ID_GRID_ROWSPACE                32803
#define ID_GRID_COLSPACE                32804
#define ID_GRID_SIZE                    32805
#define ID_32806                        32806
#define ID_FONT_COLOR                   32807
#define ID_FONT_HOLLOW                  32808
#define ID_LINE_STYLE                   32810
#define ID_LINE_STYLE1                  32820
#define ID_LINE_STYLE2                  32821
#define ID_LINE_STYLE3                  32822
#define ID_LINE_STYLE4                  32823
#define ID_LINE_STYLE5                  32824
#define ID_LINE_STYLE6                  32825
#define ID_LINE_STYLE7                  32826
#define ID_LINE_STYLE8                  32827
#define ID_32828                        32828
#define ID_FONT_SOLID                   32829
#define ID_32830                        32830
#define ID_32831                        32831
#define ID_32832                        32832
#define ID_32833                        32833
#define ID_32834                        32834
#define ID_32835                        32835
#define ID_CHAR_DIRECT                  32836
#define ID_CHAR_DIRECT1                 32837
#define ID_CHAR_DIRECT2                 32838
#define ID_CHAR_DIRECT3                 32839
#define ID_CHAR_DIRECT4                 32840
#define ID_32841                        32841
#define ID_32842                        32842
#define ID_32843                        32843
#define ID_32844                        32844
#define ID_32845                        32845
#define ID_32846                        32846
#define ID_32847                        32847
#define ID_32848                        32848
#define ID_PAGE_MARGIN_LEFT             32849
#define ID_PAGE_MARGIN_BOTTOM           32850
#define ID_PAGE_MARGIN_TOP              32851
#define ID_PAGE_MARGIN_RIGHT            32852
#define ID_CENTER_H                     32853
#define ID_CENTER_V                     32854
#define ID_32855                        32855
#define ID_PAPER_LANDSCAPE              32856
#define ID_PAPER_PORTRAIT               32857
#define ID_32858                        32858
#define ID_32859                        32859
#define ID_32860                        32860
#define ID_32861                        32861
#define ID_HUI_IN_OUT_RATE              32862
#define ID_HUI_W_H_RATE                 32863
#define ID_HUI_OFFSETY                  32864
#define ID_CHAR_OFFSETY                 32865
#define ID_VIEW_TASKPANE                32866
#define ID_32867                        32867
#define ID_32868                        32868
#define ID_TASKPANE_GRID_SPLIT          32869
#define ID_STATUS_PANE                  32870
#define ID_OWNERDRAWGRID                32871
#define ID_32872                        32872
#define ID_OPENDRAWIMG                  32873
#define ID_32874                        32874
#define ID_SAVEDRAWIMG                  32875
#define ID_32876                        32876
#define ID_EDITIMG                      32877
#define ID_32878                        32878
#define ID_OWNERDRAWPREVIEW             32879
#define ID_32880                        32880
#define ID_BACKGROUND                   32881
#define ID_COMMAND_MAX                  33000

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        334
#define _APS_NEXT_COMMAND_VALUE         32887
#define _APS_NEXT_CONTROL_VALUE         1006
#define _APS_NEXT_SYMED_VALUE           311
#endif
#endif
